
# Files generated by Windows build

WIN_CLEANUP = config.nice.bat Release_TS configure.bat configure.js

PHPC_CMD = $(PHP_EXECUTABLE) -r 'PCS\Embedded\build();' --

.PHONY: phpc ex1.phpc

#-----------------------

phpc: ex1.phpc

ex1.phpc:
	$(PHPC_CMD) $(srcdir)/pcs/php $(srcdir)/pcs/phpc/$@

#-----------------------

cleanup: clean
	phpize --clean
	@rm -rf $(WIN_CLEANUP) include modules
